
import { TokenProvider } from '../shared/providers/TokenProvider';
import { EmailProvider } from '../shared/providers/EmailProvider';
import { HashProvider } from '../shared/providers/HashProvider';
import { ActivityHistoryRepository } from '../modules/audit/repositories/ActivityHistoryRepository';
import { AuditLogRepository } from '../modules/audit/repositories/AuditLogRepository';
import { MembershipRepository } from '../modules/team/repositories/MembershipRepository';
import { NotificationRepository } from '../modules/notification/repositories/NotificationRepository';
import { PasswordResetRepository } from '../modules/auth/repositories/PasswordResetRepository';
import { PendingUserRepository } from '../modules/auth/repositories/PendingUserRepository';
import { RoleAssignmentRepository } from '../modules/access-control/repositories/RoleAssignmentRepository';
import { RoleRepository } from '../modules/access-control/repositories/RoleRepository';
import { TeamRepository } from '../modules/team/repositories/TeamRepository';
import { UserRepository } from '../modules/user/repositories/UserRepository';
import { WorkshopProjectRepository } from '../modules/project/repositories/WorkshopProjectRepository';
import { WorkshopRepository } from '../modules/workshop/repositories/WorkshopRepository';
import { WorkshopTaskRepository } from '../modules/task/repositories/WorkshopTaskRepository';
import { ActivityHistoryService } from '../modules/audit/services/ActivityHistoryService';
import { AuditService } from '../modules/audit/services/AuditService';
import { AuthService } from '../modules/auth/services/AuthService';
import { ChatService } from '../modules/chat/services/ChatService';
import { CloudinaryService } from '../shared/services/CloudinaryService';
import { EmailService } from '../shared/services/EmailService';
import { NotificationService } from '../modules/notification/services/NotificationService';
import { PermissionService } from '../modules/access-control/services/PermissionService';
import { SocketService } from '../socket/SocketService';
import { TeamService } from '../modules/team/services/TeamService';
import { WorkshopProjectService } from '../modules/project/services/WorkshopProjectService';
import { WorkshopService } from '../modules/workshop/services/WorkshopService';
import { WorkshopTaskService } from '../modules/task/services/WorkshopTaskService';
import { ActivityController } from '../modules/audit/controllers/ActivityController';
import { AuditController } from '../modules/audit/controllers/AuditController';
import { AuthController } from '../modules/auth/controllers/AuthController';
import { ChatController } from '../modules/chat/controllers/ChatController';
import { InviteController } from '../modules/invitation/controllers/InviteController';
import { NotificationController } from '../modules/notification/controllers/NotificationController';
import { PermissionController } from '../modules/access-control/controllers/PermissionController';
import { RoleController } from '../modules/access-control/controllers/RoleController';
import { TeamController } from '../modules/team/controllers/TeamController';
import { WorkshopController } from '../modules/workshop/controllers/WorkshopController';
import { WorkshopProjectController } from '../modules/project/controllers/WorkshopProjectController';
import { WorkshopTaskController } from '../modules/task/controllers/WorkshopTaskController';

export interface Container {
    tokenProv: TokenProvider;
    emailProv: EmailProvider;
    hashProv: HashProvider;

    activityHistoryRepo: ActivityHistoryRepository;
    auditLogRepo: AuditLogRepository;
    membershipRepo: MembershipRepository;
    notificationRepo: NotificationRepository;
    passwordResetRepo: PasswordResetRepository;
    pendingUserRepo: PendingUserRepository;
    roleAssignmentRepo: RoleAssignmentRepository;
    roleRepo: RoleRepository;
    teamRepo: TeamRepository;
    userRepo: UserRepository;
    workshopProjectRepo: WorkshopProjectRepository;
    workshopRepo: WorkshopRepository;
    workshopTaskRepo: WorkshopTaskRepository;

    activityHistorySrv: ActivityHistoryService;
    auditSrv: AuditService;
    authSrv: AuthService;
    chatSrv: ChatService;
    cloudinarySrv: CloudinaryService;
    emailSrv: EmailService;
    notificationSrv: NotificationService;
    permissionSrv: PermissionService;
    socketSrv: SocketService;
    teamSrv: TeamService;
    workshopProjectSrv: WorkshopProjectService;
    workshopSrv: WorkshopService;
    workshopTaskSrv: WorkshopTaskService;

    activityCtrl: ActivityController;
    auditCtrl: AuditController;
    authCtrl: AuthController;
    chatCtrl: ChatController;
    inviteCtrl: InviteController;
    notificationCtrl: NotificationController;
    permissionCtrl: PermissionController;
    roleCtrl: RoleController;
    teamCtrl: TeamController;
    workshopCtrl: WorkshopController;
    workshopProjectCtrl: WorkshopProjectController;
    workshopTaskCtrl: WorkshopTaskController;
}
