
import { ITokenProvider } from '../shared/interfaces/ITokenProvider';
import { IEmailProvider } from '../shared/interfaces/IEmailProvider';
import { IHashProvider } from '../shared/interfaces/IHashProvider';
import { IActivityHistoryRepository } from '../modules/audit/interfaces/IActivityHistoryRepository';
import { IAuditLogRepository } from '../modules/audit/interfaces/IAuditLogRepository';
import { IMembershipRepository } from '../modules/team/interfaces/IMembershipRepository';
import { INotificationRepository } from '../modules/notification/interfaces/INotificationRepository';
import { IPasswordResetRepository } from '../modules/auth/interfaces/IPasswordResetRepository';
import { IPendingUserRepository } from '../modules/auth/interfaces/IPendingUserRepository';
import { IRoleAssignmentRepository } from '../modules/access-control/interfaces/IRoleAssignmentRepository';
import { IRoleRepository } from '../modules/access-control/interfaces/IRoleRepository';
import { ITeamRepository } from '../modules/team/interfaces/ITeamRepository';
import { IUserRepository } from '../modules/user/interfaces/IUserRepository';
import { IWorkshopProjectRepository } from '../modules/project/interfaces/IWorkshopProjectRepository';
import { IWorkshopRepository } from '../modules/workshop/interfaces/IWorkshopRepository';
import { IWorkshopTaskRepository } from '../modules/task/interfaces/IWorkshopTaskRepository';
import { IActivityHistoryService } from '../modules/audit/interfaces/IActivityHistoryService';
import { IAuditService } from '../modules/audit/interfaces/IAuditService';
import { IAuthService } from '../modules/auth/interfaces/IAuthService';
import { IChatService } from '../modules/chat/interfaces/IChatService';
import { ICloudinaryService } from '../shared/interfaces/ICloudinaryService';
import { IEmailService } from '../shared/interfaces/IEmailService';
import { INotificationService } from '../modules/notification/interfaces/INotificationService';
import { IPermissionService } from '../modules/access-control/interfaces/IPermissionService';
import { ISocketService } from '../shared/interfaces/ISocketService';
import { ITeamService } from '../modules/team/interfaces/ITeamService';
import { IWorkshopProjectService } from '../modules/project/interfaces/IWorkshopProjectService';
import { IWorkshopService } from '../modules/workshop/interfaces/IWorkshopService';
import { IWorkshopTaskService } from '../modules/task/interfaces/IWorkshopTaskService';
import { ActivityController } from '../modules/audit/controllers/ActivityController';
import { AuditController } from '../modules/audit/controllers/AuditController';
import { AuthController } from '../modules/auth/controllers/AuthController';
import { ChatController } from '../modules/chat/controllers/ChatController';
import { InviteController } from '../modules/invitation/controllers/InviteController';
import { NotificationController } from '../modules/notification/controllers/NotificationController';
import { PermissionController } from '../modules/access-control/controllers/PermissionController';
import { RoleController } from '../modules/access-control/controllers/RoleController';
import { TeamController } from '../modules/team/controllers/TeamController';
import { WorkshopController } from '../modules/workshop/controllers/WorkshopController';
import { WorkshopProjectController } from '../modules/project/controllers/WorkshopProjectController';
import { WorkshopTaskController } from '../modules/task/controllers/WorkshopTaskController';
import { IInvitationService } from '../modules/invitation/interfaces/IInvitationService';
import { IInvitationRepository } from '../modules/invitation/interfaces/IInvitationRepository';

export interface Container {
    tokenProv: ITokenProvider;
    emailProv: IEmailProvider;
    hashProv: IHashProvider;

    activityHistoryRepo: IActivityHistoryRepository;
    auditLogRepo: IAuditLogRepository;
    membershipRepo: IMembershipRepository;
    notificationRepo: INotificationRepository;
    passwordResetRepo: IPasswordResetRepository;
    pendingUserRepo: IPendingUserRepository;
    roleAssignmentRepo: IRoleAssignmentRepository;
    invitationRepo: IInvitationRepository;
    roleRepo: IRoleRepository;
    teamRepo: ITeamRepository;
    userRepo: IUserRepository;
    workshopProjectRepo: IWorkshopProjectRepository;
    workshopRepo: IWorkshopRepository;
    workshopTaskRepo: IWorkshopTaskRepository;

    activityHistorySrv: IActivityHistoryService;
    auditSrv: IAuditService;
    authSrv: IAuthService;
    chatSrv: IChatService;
    cloudinarySrv: ICloudinaryService;
    emailSrv: IEmailService;
    invitationSrv: IInvitationService;
    notificationSrv: INotificationService;
    permissionSrv: IPermissionService;
    socketSrv: ISocketService;
    teamSrv: ITeamService;
    workshopProjectSrv: IWorkshopProjectService;
    workshopSrv: IWorkshopService;
    workshopTaskSrv: IWorkshopTaskService;

    activityCtrl: ActivityController;
    auditCtrl: AuditController;
    authCtrl: AuthController;
    chatCtrl: ChatController;
    inviteCtrl: InviteController;
    notificationCtrl: NotificationController;
    permissionCtrl: PermissionController;
    roleCtrl: RoleController;
    teamCtrl: TeamController;
    workshopCtrl: WorkshopController;
    workshopProjectCtrl: WorkshopProjectController;
    workshopTaskCtrl: WorkshopTaskController;
}
